### ISSUE TITLE
Cannot find namespace 'Socket  IOClient'

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxf/platform#8]
Hi,
I am trying to install your package with angular 7.2.*

However, I am getting the following when I import the modules in my App.component.ts file

```
node_modules/@ngxf/socket.io/lib/directives/socket.io.directive.d.ts(3,16): error TS2503: Cannot find namespace 'Socket 
 IOClient'. 
 node_modules/@ngxf/socket.io/lib/directives/socket.io.on.directive.d.ts(10,21): error TS2503: Cannot find namespace 'SocketIOCli 
 ent'. 
```

Does the package suppports angular 7.x.x

**Comment by thekiba** [comment]
Hello, did you install `socket.io-client` and `@types/socket.io-client`?

**Comment by st-clair-clarke** [comment]
No, I did not. Install them now and app now working again. 

Please add your answer to the installation section of the documentary.

Thanks.

**Comment by thekiba** [comment]
I added it to the documentation, thanks!
